exps <- c("exp34",
         "exp35",
         "exp36",
         "exp37",
         "exp38",
         "exp39",
         "exp40",
         "exp41",
         "exp42",
         "exp43",
         "exp44",
         "exp45",
         "exp28",
         "exp29",
         "exp30",
         "exp31",
         "exp32",
         "exp33")
waste_ts_viscosity <- waste_ts_sorted[which(waste_ts_sorted[,"experiment"]%in%exps),]
